### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by msrivastav13** [SFDO-Tooling/homebrew-sfdo#66]
I get this error in mac terminal as below

`brew tap SFDO-Tooling/homebrew-sfdo && brew install cumulusci`

Python 3 is successfully installed

**Error in terminal**

`==> python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Ce
Last 15 lines from /Users/mohith/Library/Logs/Homebrew/cumulusci/08.python3:
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 687, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1066, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1078, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 743, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/local/lib/python3.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/usr/local/opt/python/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/private/tmp/tmpck3hgak1', '--quiet', 'pycparser']' returned non-zero exit status 2.`

This is when i am following installation instructions here (https://trailhead.salesforce.com/content/learn/modules/cumulusci-setup/install-cumulusci?trail_id=build-applications-with-cumulusci)

**Comment by davisagli** [comment]
@msrivastav13 hi, it looks like the installation is using the wrong copy of Python 3 (from /usr/local/opt/python/bin instead of from /usr/local/bin where homebrew installs it). Does it work any better if you try running `brew install cumulusci` a second time?

**Comment by msrivastav13** [comment]
No it does not . I get this error

`python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Ce
Last 15 lines from /Users/mohith/Library/Logs/Homebrew/cumulusci/08.python3:
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 687, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1066, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1078, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 743, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/local/lib/python3.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/usr/local/opt/python/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/private/tmp/tmpqe5rqb2p', '--quiet', 'pycparser']' returned non-zero exit status 2.`

**Comment by davisagli** [comment]
@msrivastav13 Try this:
`PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin brew install cumulusci`

The idea is to run the installation with a temporary change to your PATH so that the installer finds the right copy of python3.

I will check if we can improve the homebrew formula so that this isn't necessary in the future.

**Comment by msrivastav13** [comment]
It still throws below error. Sorry i am new python so i am having hard time on this.

`python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Ce
Last 15 lines from /Users/mohith/Library/Logs/Homebrew/cumulusci/10.python3:
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 687, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1066, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1078, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 743, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/local/lib/python3.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/usr/local/opt/python/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/private/tmp/tmpkqgzchw6', '--quiet', 'pycparser']' returned non-zero exit status 2.`

**Comment by davisagli** [comment]
@msrivastav13 sorry that I haven't been more helpful -- it's a little hard to tell what is going wrong. The error you keep sharing looks like a small portion of the full output from the brew command. Is it possible to show more of it in case that gives any clues?

**Comment by msrivastav13** [comment]
Yes sure. Let me attach the full output

[10.python3.txt](https://github.com/SFDO-Tooling/homebrew-sfdo/files/4343714/10.python3.txt)

**Comment by msrivastav13** [comment]
@davisagli attached the full output.

**Comment by davisagli** [comment]
@msrivastav13 could I also see the output from `brew doctor`? This is a diagnostic command for Homebrew that will check to make sure things are set up correctly.

**Comment by msrivastav13** [comment]
`Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/node/ares.h
  /usr/local/include/node/ares_build.h
  /usr/local/include/node/ares_rules.h
  /usr/local/include/node/ares_version.h
  /usr/local/include/node/js_native_api.h
  /usr/local/include/node/js_native_api_types.h
  /usr/local/include/node/nameser.h
  /usr/local/include/node/smalloc.h
  /usr/local/include/node/uv/aix.h
  /usr/local/include/node/uv/android-ifaddrs.h
  /usr/local/include/node/uv/bsd.h
  /usr/local/include/node/uv/darwin.h
  /usr/local/include/node/uv/errno.h
  /usr/local/include/node/uv/linux.h
  /usr/local/include/node/uv/os390.h
  /usr/local/include/node/uv/posix.h
  /usr/local/include/node/uv/stdint-msvc2008.h
  /usr/local/include/node/uv/sunos.h
  /usr/local/include/node/uv/threadpool.h
  /usr/local/include/node/uv/tree.h
  /usr/local/include/node/uv/unix.h
  /usr/local/include/node/uv/version.h
  /usr/local/include/node/uv/win.h
  /usr/local/include/node/v8-experimental.h
  /usr/local/include/node/v8stdint.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  heroku

Warning: An outdated version (2.13.4) of Git was detected in your PATH.
Git 2.14.3 or newer is required for Homebrew.
Please upgrade:
  brew upgrade git

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/bin/apm
  /usr/local/bin/atom
  /usr/local/bin/cordova
  /usr/local/bin/create-react-app
  /usr/local/bin/docker
  /usr/local/bin/docker-compose
  /usr/local/bin/docker-credential-osxkeychain
  /usr/local/bin/docker-machine
  /usr/local/bin/force-server
  /usr/local/bin/forceios
  /usr/local/bin/hyperkit
  /usr/local/bin/jsforce
  /usr/local/bin/notary
  /usr/local/bin/package-xml
  /usr/local/bin/serve
  /usr/local/bin/vpnkit
  /usr/local/etc/bash_completion.d/_brew_services

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install gettext libidn2 libunistring openjdk

Run `brew missing` for more details.
`

**Comment by msrivastav13** [comment]
@davisagli above is what i see

**Comment by msrivastav13** [comment]
@davisagli Any update on this ? Let me know if we need a zoom meeting. I am blocked on this and looking for some assistance.

**Comment by davisagli** [comment]
@msrivastav13 I am planning to do some work on the homebrew installer to try to handle this situation better (when the python3 command found on your PATH is different from the one installed by homebrew). But this may take some time.

In the meantime since you already have python3 you can try installing a different way:
1. In the terminal, run `python3 -m pip install pipx`
2. Run `pipx install cumulusci` (pipx will create a "virtualenv" to keep cumulusci and its dependencies isolated from your main Python packages)
3. Make sure you follow the instructions that pipx displays for updating your PATH to include the bin directory where it installed the cci command.

**Comment by msrivastav13** [comment]
on doing 1 i get the below error

`ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 899, in find_requirement
    req.name, specifier=req.specifier, hashes=hashes,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 881, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 826, in find_all_candidates
    project_url, link_evaluator=link_evaluator,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 790, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 497, in fetch_page
    return _get_html_page(location, session=self.session)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 337, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 143, in _get_html_response
    "Cache-Control": "max-age=0",
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/network/session.py", line 405, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 524, in request
    prep.url, proxies, stream, verify, cert
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 700, in merge_environment_settings
    env_proxies = get_environ_proxies(url, no_proxy=no_proxy)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/requests/utils.py", line 761, in get_environ_proxies
    if should_bypass_proxies(url, no_proxy=no_proxy):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/requests/utils.py", line 745, in should_bypass_proxies
    bypass = proxy_bypass(parsed.hostname)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2614, in proxy_bypass
    return proxy_bypass_macosx_sysconf(host)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2591, in proxy_bypass_macosx_sysconf
    return _proxy_bypass_macosx_sysconf(host, proxy_settings)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2577, in _proxy_bypass_macosx_sysconf
    if (hostIP >> mask) == (base >> mask):
ValueError: negative shift count`

**Comment by davisagli** [comment]
Hmm, that is the same error that happened during the homebrew install, and it looks like the error is coming from Python itself rather than from our installers. It looks like it is happening when it tries to fetch a package from the Python Package Index and it is having trouble using your proxy settings. Do you have a proxy configured in your system network settings?

**Comment by msrivastav13** [comment]
No I am not aware of any network proxy on my system.I will check to see if there are any.

**Comment by msrivastav13** [comment]
@davisagli Yes i had a bypass proxy turned on for few domains like "*.local, 169.254/161" that was causing this issue.

I turned it off and it did build fine. Thank you for all the support in helping me figure the cause of the issue

**Comment by davisagli** [comment]
On my Mac the bypass proxy is set to "*.local, 169.254/16" -- I have never configured that, so I think it must be a default and your problem was the extra 1 at the end which turned it into an invalid netmask. Anyway, glad you are able to move forward.
